# Generated by Django 5.1.1 on 2024-09-07 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_party_options_party_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='guest',
            name='meal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.mealoption'),
        ),
    ]
