# Generated by Django 5.1.1 on 2024-09-07 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_guest_attending'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='guest',
            name='meal',
        ),
        migrations.AddField(
            model_name='mealoption',
            name='event',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='main.event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='party',
            name='events',
            field=models.ManyToManyField(related_name='invitees', to='main.event'),
        ),
        migrations.CreateModel(
            name='EventInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attending', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_invites', to='main.event')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_invites', to='main.guest')),
                ('meal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.mealoption')),
            ],
        ),
    ]
