# Generated by Django 5.1.1 on 2024-09-07 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_event_remove_guest_meal_mealoption_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventinvite',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_invites', to='main.event'),
        ),
    ]
