# Generated by Django 5.1.1 on 2024-09-08 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_event_date_event_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='dietary_preferences',
            new_name='dietary_restrictions',
        ),
    ]
