# Generated by Django 5.1.1 on 2024-11-01 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_dietary_preferences_guest_dietary_restrictions'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='about',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
