# Generated by Django 5.1.1 on 2024-12-10 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_galleryphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryphoto',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
