# Generated by Django 5.1.1 on 2024-12-10 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_qrcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryphoto',
            name='thumbnail_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
