# Generated by Django 5.1.1 on 2024-12-10 18:17

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_galleryphoto_thumbnail_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryphoto',
            name='order',
            field=models.IntegerField(default=main.models.GalleryPhoto.default_order),
        ),
    ]
