# Generated by Django 4.2.17 on 2025-03-22 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_galleryphoto_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='suggestion',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
